default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('DATABASE_USER') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bugno_development

test:
  <<: *default
  database: bugno_test

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: bugno_production
